package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "smartereye_proto",
    deps = [
        ":smartereye_proto_lib",
    ],
)

proto_library(
    name = "smartereye_proto_lib",
    srcs = [
        "smartereye_conf.proto",
    ],
)
